import type { PageFlags, IProtocol } from "@/types/general"

export const pages: Record<IProtocol['protocol'], PageFlags> = {
    "compound": {
        "projects": true,       
        "github": true,
        "forum": true,
        "governance": true,
        "developers": true,
        "leaderboard": true,
    },
    "flow": {
        "projects": true,
        "github": true,
        "forum": true,
        "governance": false,
        "developers": true,
        "leaderboard": true,
    },
    "lens": {
        "projects": true,
        "github": true,
        "forum": false,
        "governance": false,
        "developers": false,
        "leaderboard": true,
    },
    "polkadot": {
        "projects": true,
        "github": true,
        "forum": true,
        "governance": false,
        "developers": true,
        "leaderboard": true,
    },
    "balancer": {
        "projects": true,
        "github": true,
        "forum": true,
        "governance": false,
        "developers": true,
        "leaderboard": true,
    },
    "aave": {
        "projects": true,
        "github": true,
        "forum": true,
        "governance": true,
        "developers": true,
        "leaderboard": true,
    },
    "proton": {
        "projects": true,
        "github": true,
        "forum": false,
        "governance": false,
        "developers": false,
        "leaderboard": true,
    },
    "osmosis": {
        "projects": true,
        "github": true,
        "forum": false,
        "governance": false,
        "developers": true,
        "leaderboard": true,
    },
    "the-graph": {
        "projects": true,
        "github": true,
        "forum": true,
        "governance": false,
        "developers": true,
        "leaderboard": true,
    },
    "ton": {
        "projects": true,
        "github": true,
        "forum": false,
        "governance": false,
        "developers": true,
        "leaderboard": true,
    },
    "ocean": {
        "projects": true,
        "github": true,
        "forum": false,
        "governance": false,
        "developers": false,
        "leaderboard": true,
    },
    "eos": {
        "projects": true,
        "github": true,
        "forum": true,
        "governance": false,
        "developers": true,
        "leaderboard": true,
    },
}