import Head from "next/head";

export default function LeaderBoard() {
  return (
    <>
      <Head>
        <title>Leaderboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <section className="container mx-auto my-12 max-w-7xl px-4 sm:px-6 lg:px-8 py-1">
        <div className="flex flex-wrap space-y-8">
          <div className="w-full">
            <h2>leaderboard</h2>
          </div>
        </div>
      </section>
    </>
  );
}
