import Head from "next/head";
import Image from "next/image";

import {
  InstantSearch,
  SearchBox,
  InfiniteHits,
  Configure,
  HierarchicalMenu,
} from "react-instantsearch-hooks-web";

import ProjectCard from "@/components/projects/ProjectCard";
import { searchClient } from "@/utils/searchClient";
import { useProtocol } from "@/models/protocols/useProtocol";
import { getSearchIndexForProtocol } from "@/utils/functions";

export default function Projects() {
  const { protocol } = useProtocol();

  return (
    <>
      <Head>
        <title>Projects - {protocol["protocol"]}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <section className="max-w-[90%] mx-auto mb-16 -mt-6 px-4 sm:px-6 lg:px-8 py-1">
        <InstantSearch
          key={protocol["protocol"]}
          searchClient={searchClient(protocol["protocol"])}
          indexName={getSearchIndexForProtocol(protocol["protocol"])}
          routing={true}
        >
          <div className="grid grid-cols-4 gap-12">
            <Configure analytics={false} hitsPerPage={9} />
            <div className="col-span-4 md:col-span-1 max-w-[430px] hidden lg:block xl:block 2xl:block bg-white shadow-lg rounded-lg p-6 border-2 border-sfblue-800">
              <div className="sticky top-[60px]">
                <div className="flex items-center justify-between text-lg font-semibold mb-4 border-b-2 pb-4 border-sfblue-700">
                  <div className="flex items-center space-x-3">
                    <Image
                      src="/flow-logo.png"
                      alt="Category Icon"
                      className="w-6 h-6"
                      width={40}
                      height={40}
                    />
                    <span className="text-sfblack">Categories</span>
                  </div>
                  <span className="bg-sfblue-700 text-white px-3 py-1 rounded-full text-sm">
                    {protocol["protocol"]}
                  </span>
                </div>

                <nav className="space-y-2 mt-4">
                  <HierarchicalMenu
                    attributes={["categories.lvl0"]}
                    showParentLevel={true}
                    classNames={{
                      root: "",
                      item: "py-2 px-3 text-lg transition-colors duration-150 hover:bg-sfblue-700 hover:text-white rounded-lg",
                      label: "flex w-full items-center text-md",
                      link: "flex w-full items-center justify-between",
                      count:
                        "text-sm bg-sfred-500 text-indigo-800 font-semibold rounded-full px-3 py-1",
                      selectedItemLink: "",
                      childList: "ml-5 mt-2 space-y-2",
                    }}
                  />
                </nav>
              </div>
            </div>

            <div className="col-span-4 md:col-span-3 mx-auto">
              <div className="container">
                <InfiniteHits
                  showPrevious={false}
                  hitComponent={(e) => <ProjectCard hit={e.hit} />}
                  classNames={{
                    list: "grid grid-cols-3 gap-8",
                    item: "2xl:col-span-1 xl:col-span-1 col-span-3",
                    disabledLoadMore: "hidden",
                    loadMore:
                      "w-full mt-10 mx-auto text-center inline-block py-3 text-center leading-6 text-lg text-white font-extrabold bg-sfblue-700 hover:bg-sfblue-800 border-3 border-indigo-900 shadow rounded transition duration-200",
                  }}
                />
              </div>
            </div>
          </div>
        </InstantSearch>
      </section>
    </>
  );
}
