import Head from "next/head";

import {
  InstantSearch,
  SearchBox,
  InfiniteHits,
  Configure,
  HierarchicalMenu,
} from "react-instantsearch-hooks-web";

import ProjectCard from "@/components/projects/ProjectCard";
import { searchClient } from "@/utils/searchClient";

export default function Projects() {
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <section className="container mx-auto my-12 max-w-7xl px-4 sm:px-6 lg:px-8 py-1">
        <InstantSearch
          searchClient={searchClient}
          indexName={process.env.NEXT_PUBLIC_INDEX_NAME as string}
          routing={true}
        >
          <div className="grid grid-cols-4 gap-16 mb-24">
            <Configure analytics={false} hitsPerPage={9} />
            <div className="col-span-4 md:col-span-1 max-w-[430px] hidden lg:block xl:block 2xl:block">
              <div className="sticky top-[60px]">
                <div className="col-span-1 sticky top-[60px] scroll-smooth">
                  <nav className="space-y-1">
                    <HierarchicalMenu
                      attributes={["categories.lvl0"]}
                      showParentLevel={true}
                      classNames={{
                        root: "-mt-3 mr-0 md:mr-4 hidden md:block",
                        item: "py-3 text-lg font-semibold",
                        label: "flex w-full pl-5",
                        link: "flex w-full",
                        count:
                          "flex-1 text-black text-[14px] mr-4 font-semibold rounded-md my-auto text-indigo-800",
                        selectedItemLink:
                          "py-3 bg-gray-100 border-[3px] border-indigo-900 rounded-xl",
                        childList: "ml-8 -mb-4",
                      }}
                    />
                  </nav>
                </div>
              </div>
            </div>

            <div className="col-span-4 block xl:hidden lg:hidden">
              <div className="col-span-1">
                <select
                  id="countries"
                  className="w-full border-[3px] border-indigo-900 text-gray-900 text-[15px] font-semibold rounded-lg py-3"
                >
                  <option value="All">All</option>
                  <option value="Algorithms 🧮">Algorithms 🧮</option>
                  <option value="Automation 🤖">Automation 🤖</option>
                  <option value="DAO Tools 🗳">DAO Tools 🗳</option>
                  <option value="Music 🎶">Music 🎶</option>
                  <option value="Gaming 🎮">Gaming 🎮</option>
                  <option value="Community 👨‍👩‍👧‍👧">Community 👨‍👩‍👧‍👧</option>
                  <option value="Monetization 💰">Monetization 💰</option>
                  <option value="Analytics 📊">Analytics 📊</option>
                  <option value="Tools 🛠">Tools 🛠</option>
                  <option value="Identity 🎭">Identity 🎭</option>
                  <option value="Social Media ❤️‍🔥">Social Media ❤️‍🔥</option>
                  <option value="Developers 👨🏼‍💻">Developers 👨🏼‍💻</option>
                  <option value="Other ✨">Other ✨</option>
                </select>
              </div>
            </div>

            <div className="col-span-4 md:col-span-3 mx-auto">
              <div className="container">
                <InfiniteHits
                  showPrevious={false}
                  hitComponent={(e) => <ProjectCard hit={e.hit} />}
                  classNames={{
                    list: "grid grid-cols-3 gap-12",
                    item: "2xl:col-span-1 xl:col-span-1 col-span-3",
                    disabledLoadMore: "hidden",
                    loadMore:
                      "w-full mt-12 mx-auto text-center inline-block py-4 text-center leading-6 text-lg text-white font-extrabold bg-indigo-800 hover:bg-indigo-900 border-3 border-indigo-900 shadow rounded transition duration-200",
                  }}
                />
              </div>
            </div>
          </div>
        </InstantSearch>
      </section>
    </>
  );
}
