import Head from "next/head";

// Sidebar
import Sidebar from "@/modules/Sidebar/Sidebar";
import SideInfo from "@/components/discourse/SideInfo";

// Discourse Components
import Categories from "@/components/discourse/Categories";
import TopicActivity from "@/components/discourse/TopicActivity";
import TopicMetrics from "@/components/discourse/TopicMetrics";
import UserMetrics from "@/components/discourse/UserMetrics";
import Tags from "@/components/discourse/Tags";
import TopTopics from "@/components/discourse/TopTopics";
import LatestTopics from "@/components/discourse/LatestTopics";
import LatestPosts from "@/components/discourse/LatestPosts";
import TopUsers from "@/components/discourse/TopUsers";

// Heroicons
import {
  ChartPieIcon,
  UserGroupIcon,
  ChartBarIcon,
  ListBulletIcon,
  PresentationChartBarIcon,
} from "@heroicons/react/24/outline";

export default function Discourse() {
  const navigation = [
    {
      name: "Forum Overview",
      href: "#forum-overview",
      icon: PresentationChartBarIcon,
      current: true,
    },
    {
      name: "Topic Activity",
      href: "#topic-activity",
      icon: ChartBarIcon,
      count: "5",
      current: false,
    },
    {
      name: "Top Topics",
      href: "#top-topics",
      icon: ListBulletIcon,
      current: false,
    },
    {
      name: "Tags",
      href: "#tags",
      icon: ChartPieIcon,
      count: "20+",
      current: false,
    },
    {
      name: "Category Distribution",
      href: "#category-distribution",
      icon: ChartPieIcon,
      count: "12",
      current: false,
    },
    {
      name: "Top Users",
      href: "#top-users",
      icon: ListBulletIcon,
      current: false,
    },
    {
      name: "User Metrics",
      href: "#user-metrics",
      icon: UserGroupIcon,
      current: false,
    },

    {
      name: "Latest Posts",
      href: "#latest-posts",
      icon: ListBulletIcon,
      current: false,
    },
    {
      name: "Latest Topics",
      href: "#latest-topics",
      icon: ListBulletIcon,
      current: false,
    },
  ];

  return (
    <>
      <Head>
        <title>Forum - Flowana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <section className="max-w-[90%] mx-auto mb-8 -mt-6 px-4 sm:px-6 lg:px-8 py-1">
        <div className="grid grid-cols-5 gap-12">
          <div className="col-span-1">
            <Sidebar navigation={navigation} element={<SideInfo />} />
          </div>
          <div className="col-span-4">
            <div className="flex flex-wrap space-y-6">
              <div id="forum-overview" className="w-full">
                <TopicMetrics />
              </div>
              <div id="topic-activity" className="w-full">
                <TopicActivity />
              </div>
              <div className="flex space-x-6 w-full">
                <div id="top-topics" className="w-full sm:w-2/3 md:w-2/3">
                  <TopTopics />
                </div>
                <div id="tags" className="w-full sm:w-1/3 md:w-1/3">
                  <Tags />
                </div>
              </div>
              <div id="category-distribution" className="w-full">
                <Categories />
              </div>
              <div className="flex space-x-6 w-full">
                <div id="top-users" className="w-full sm:w-2/3 md:w-2/3">
                  <TopUsers />
                </div>
                <div id="user-metrics" className="w-full sm:w-1/3 md:w-1/3">
                  <UserMetrics />
                </div>
              </div>
              <div id="latest-posts" className="w-full">
                <LatestPosts />
              </div>
              <div id="latest-topics" className="w-full">
                <LatestTopics />
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
