import Head from "next/head";

// Sidebar
import Sidebar from "@/modules/Sidebar/Sidebar";
import SideInfo from "@/components/developers/SideInfo";

// Developer Components
import Stats from "@/components/developers/Stats";
import DevTypeTable from "@/components/developers/DevTypeTable";
import MonthlyCommitsByDevTypeChart from "@/components/developers/MonthlyCommitsByDevTypeChart";
import MonthlyActiveDevChart from "@/components/developers/MonthlyActiveDevChart";
import MonthlyCommitsChart from "@/components/developers/MonthlyCommitsChart";
import TotalMonthlyActiveDevChart from "@/components/developers/TotalMonthlyActiveDevChart";

// Heroicons
import {
  TableCellsIcon,
  MagnifyingGlassIcon,
  ChartBarIcon,
} from "@heroicons/react/24/outline";

export default function Developers() {
  const navigation = [
    {
      name: "Developer Overview",
      href: "#developer-overview",
      icon: MagnifyingGlassIcon,
      current: true,
    },
    {
      name: "Developer Types",
      href: "#developer-types",
      icon: TableCellsIcon,
      current: false,
    },
    {
      name: "Total Active Devs",
      href: "#total-active-devs",
      icon: ChartBarIcon,
      current: false,
    },
    {
      name: "Commit Trends by Devs",
      href: "#commit-trends-by-devs",
      icon: ChartBarIcon,
      current: false,
    },
    {
      name: "Monthly Active Devs",
      href: "#monthly-active-devs",
      icon: ChartBarIcon,
      current: false,
    },
    {
      name: "Monthly Commits",
      href: "#monthly-commits",
      icon: ChartBarIcon,
      current: false,
    },
  ];

  return (
    <>
      <Head>
        <title>Developers - Flowana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <section className="max-w-[95%] md:max-w-[90%] mx-auto mb-8 mt-6 md:-mt-6 px-4 sm:px-6 lg:px-8 py-1">
        <div className="grid grid-cols-5 gap-12">
          <div className="md:col-span-1 md:block hidden">
            <Sidebar navigation={navigation} element={<SideInfo />} />
          </div>
          <div className="md:col-span-4 col-span-5">
            <div className="flex flex-wrap space-y-8">
              <div id="developer-overview" className="w-full">
                <Stats />
              </div>
              <div id="developer-types" className="w-full">
                <DevTypeTable />
              </div>
              <div id="total-active-devs" className="w-full">
                <TotalMonthlyActiveDevChart />
              </div>
              <div id="commit-trends-by-devs" className="w-full">
                <MonthlyCommitsByDevTypeChart />
              </div>
              <div id="monthly-active-devs" className="w-full">
                <MonthlyActiveDevChart />
              </div>
              <div id="monthly-commits" className="w-full">
                <MonthlyCommitsChart />
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
