import Head from "next/head";

import DevTypeTable from "@/components/developers/DevTypeTable";
import FullTime from "@/components/developers/FullTime";
import MonthlyActiveDevs from "@/components/developers/MonthlyActiveDevs";
import TotalCommits from "@/components/developers/TotalCommits";
import TotalRepos from "@/components/developers/TotalRepos";
import MonthlyCommitsByDevTypeChart from "@/components/developers/MonthlyCommitsByDevTypeChart";
import MonthlyActiveDevChart from "@/components/developers/MonthlyActiveDevChart";
import MonthlyCommitsChart from "@/components/developers/MonthlyCommitsChart";
import TotalMonthlyActiveDevChart from "@/components/developers/TotalMonthlyActiveDevChart";

export default function Developers() {
  return (
    <>
      <Head>
        <title>Developers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <section className="container mx-auto my-12 max-w-7xl px-4 sm:px-6 lg:px-8 py-1">
        <div className="flex flex-wrap space-y-8">
          <div className="flex space-x-6 w-full">
            <div className="w-full sm:w-1/2 md:w-1/4">
              <FullTime />
            </div>
            <div className="w-full sm:w-1/2 md:w-1/4">
              <MonthlyActiveDevs />
            </div>
            <div className="w-full sm:w-1/2 md:w-1/4">
              <TotalCommits />
            </div>
            <div className="w-full sm:w-1/2 md:w-1/4">
              <TotalRepos />
            </div>
          </div>
          <div className="w-full">
            <DevTypeTable />
          </div>
          <div className="w-full">
            <TotalMonthlyActiveDevChart />
          </div>
          <div className="w-full">
            <MonthlyCommitsByDevTypeChart />
          </div>
          <div className="w-full">
            <MonthlyActiveDevChart />
          </div>
          <div className="w-full">
            <MonthlyCommitsChart />
          </div>
        </div>
      </section>
    </>
  );
}
