import Head from "next/head";

//Sidebar
import Sidebar from "@/modules/Sidebar/Sidebar";
import SideInfo from "@/components/governance/SideInfo";

import Info from "@/components/governance/Info";
import VotingPower from "@/components/governance/VotingPower";
import Proposals from "@/components/governance/Proposals";
import Safes from "@/components/governance/Safes";
import Delegates from "@/components/governance/Delegates";

// Heroicons
import {
  ChartBarIcon,
  HomeIcon,
  ListBulletIcon,
} from "@heroicons/react/24/outline";

export default function Governance() {
  const navigation = [
    {
      name: "Overview",
      href: "#overview",
      icon: HomeIcon,
      current: true,
    },
    {
      name: "Proposals",
      href: "#proposals",
      icon: ListBulletIcon,
      current: false,
    },
    {
      name: "Delegates",
      href: "#delegates",
      icon: ListBulletIcon,
      current: false,
    },
    {
      name: "Voting Power",
      href: "#voting-power",
      icon: ChartBarIcon,
      current: false,
    },
    {
      name: "Safes",
      href: "#safes",
      icon: ListBulletIcon,
      current: false,
    },
  ];

  return (
    <>
      <Head>
        <title>Governance- Flowana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <section className="max-w-[90%] mx-auto mb-8 -mt-6 px-4 sm:px-6 lg:px-8 py-1">
        <div className="grid grid-cols-5 gap-12">
          <div className="md:col-span-1 md:block hidden">
            <Sidebar navigation={navigation} element={<SideInfo />} />
          </div>
          <div className="md:col-span-4 col-span-5">
            <div className="flex flex-wrap space-y-8">
              <div id="overview" className="w-full">
                <Info />
              </div>
              <div id="proposals" className="w-full">
                <Proposals />
              </div>
              <div id="delegates" className="w-full">
                <Delegates />
              </div>
              <div id="voting-power" className="w-full">
                <VotingPower />
              </div>
              <div id="safes" className="w-full">
                <Safes />
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
